/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.18.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.kubernetes.client.examples.models;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ConfigClientSpec defines the desired state of ConfigClient
 */
@ApiModel(description = "ConfigClientSpec defines the desired state of ConfigClient")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen",
		date = "2020-12-04T15:50:40.049Z[Etc/UTC]")
public class V1ImageSpec {

	public static final String SERIALIZED_NAME_IMAGE = "image";

	@SerializedName(SERIALIZED_NAME_IMAGE)
	private String image;

	public V1ImageSpec url(String image) {

		this.image = image;
		return this;
	}

	/**
	 * Get url
	 * @return url
	 **/
	@javax.annotation.Nullable
	@ApiModelProperty(value = "")
	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		V1ImageSpec v1ImageSpec = (V1ImageSpec) o;
		return Objects.equals(this.image, v1ImageSpec.image);
	}

	@Override
	public int hashCode() {
		return Objects.hash(image);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class V1ImageSpec {\n");
		sb.append("    image: ").append(toIndentedString(image)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the
	 * first line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
